name: SurvivalSystem
version: '1.0-SNAPSHOT'
main: dev.laux.survivalsystem.SurvivalSystem
api-version: '1.20'
commands:
  sethome:
    description: Setzt dein Zuhause.
  home:
    description: Teleportiert dich zu deinem Zuhause.
  lastdeath:
    description: Teleportiere dich zu der Position deines letzten Todes.
  toggletimber:
    description: Toggle Timber feature on or off.
  job:
    description: Change your job.s
    usage: /job <jobName>